// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpcxkeczzuktgvedvllr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwY3hrZWN6enVrdGd2ZWR2bGxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MDA5OTgsImV4cCI6MjA2Nzk3Njk5OH0.bVN6iAVnTgErJL1CWY2xNQT7_XR6hAdcdcVCyBY45G8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});